# pip install numpy

In [1]:
import numpy as np

In [3]:
np.__version__

'2.3.4'

In [4]:
np.__doc__

'\nNumPy\n=====\n\nProvides\n  1. An array object of arbitrary homogeneous items\n  2. Fast mathematical operations over arrays\n  3. Linear Algebra, Fourier Transforms, Random Number Generation\n\nHow to use the documentation\n----------------------------\nDocumentation is available in two forms: docstrings provided\nwith the code, and a loose standing reference guide, available from\n`the NumPy homepage <https://numpy.org>`_.\n\nWe recommend exploring the docstrings using\n`IPython <https://ipython.org>`_, an advanced Python shell with\nTAB-completion and introspection capabilities.  See below for further\ninstructions.\n\nThe docstring examples assume that `numpy` has been imported as ``np``::\n\n  >>> import numpy as np\n\nCode snippets are indicated by three greater-than signs::\n\n  >>> x = 42\n  >>> x = x + 1\n\nUse the built-in ``help`` function to view a function\'s docstring::\n\n  >>> help(np.sort)\n  ... # doctest: +SKIP\n\nFor some objects, ``np.info(obj)`` may provide add

In [5]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [6]:
np.array([1, 2, 3])

array([1, 2, 3])

In [7]:
np.array([1, 2, 3.32])

array([1.  , 2.  , 3.32])

In [8]:
arr = np.array([1, 2, 3.32])
arr, arr.dtype

(array([1.  , 2.  , 3.32]), dtype('float64'))

In [9]:
arr = np.array([1, 2, 4])
arr, arr.dtype

(array([1, 2, 4]), dtype('int64'))

In [11]:
arr = np.array([1, 2, 4, True])
arr, arr.dtype

(array([1, 2, 4, 1]), dtype('int64'))

In [14]:
arr = np.array([1, 2, 3.32, "hello"])
arr, arr.dtype, arr.shape

(array(['1', '2', '3.32', 'hello'], dtype='<U32'), dtype('<U32'), (4,))

In [19]:
x = [[2, 3, 4, 5], ["alb", "verde", 23, 30]]
arr = np.array(x)
arr, arr.shape

(array([['2', '3', '4', '5'],
        ['alb', 'verde', '23', '30']], dtype='<U21'),
 (2, 4))

In [20]:
arr.reshape((4, 2))

array([['2', '3'],
       ['4', '5'],
       ['alb', 'verde'],
       ['23', '30']], dtype='<U21')

In [21]:
arr.reshape((8, 1))

array([['2'],
       ['3'],
       ['4'],
       ['5'],
       ['alb'],
       ['verde'],
       ['23'],
       ['30']], dtype='<U21')

In [22]:
arr.reshape((8, ))

array(['2', '3', '4', '5', 'alb', 'verde', '23', '30'], dtype='<U21')

# Generare numere folosind range

In [23]:
arr = np.array(range(100))
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [24]:
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [25]:
arr = np.arange(100, dtype=np.float64)
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [26]:
arr.reshape(4, 25)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37.,
        38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [50., 51., 52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62.,
        63., 64., 65., 66., 67., 68., 69., 70., 71., 72., 73., 74.],
       [75., 76., 77., 78., 79., 80., 81., 82., 83., 84., 85., 86., 87.,
        88., 89., 90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]])

In [27]:
arr = np.arange(100, 200, 25)
arr

array([100, 125, 150, 175])

# Generare numere random in numpy

In [28]:
import random

In [33]:
random.random()

0.6407875253207084

In [34]:
random.random()

0.8365818091077329

In [39]:
random.randint(0, 10)

3

In [68]:
random.randint(0, 10)

10

In [69]:
np.random.randint(0, 10)

5

In [70]:
np.random.randint(0, 10, 20)

array([3, 1, 8, 0, 5, 4, 9, 6, 0, 6, 0, 0, 3, 0, 9, 3, 5, 8, 7, 0])

In [71]:
np.random.randint(0, 10, (3, 6))

array([[8, 9, 7, 6, 7, 2],
       [8, 9, 1, 1, 5, 4],
       [2, 4, 4, 9, 3, 9]])

In [72]:
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [73]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [74]:
np.linspace(50, 100, 6)

array([ 50.,  60.,  70.,  80.,  90., 100.])

# Operatii pe numpy array

In [76]:
array = np.linspace(50, 100, 6)
type(array)

numpy.ndarray

In [77]:
array 

array([ 50.,  60.,  70.,  80.,  90., 100.])

# 1. Map

In [78]:
array / 10

array([ 5.,  6.,  7.,  8.,  9., 10.])

In [81]:
array - 15

array([35., 45., 55., 65., 75., 85.])

In [82]:
array1 = np.linspace(50, 100, 6)
array2 = np.linspace(100, 200, 6)

In [83]:
array1, array2

(array([ 50.,  60.,  70.,  80.,  90., 100.]),
 array([100., 120., 140., 160., 180., 200.]))

In [84]:
array1 - array2

array([ -50.,  -60.,  -70.,  -80.,  -90., -100.])

In [86]:
array3 = np.linspace(100, 200, 5)
array3

array([100., 125., 150., 175., 200.])

In [87]:
array1 - array3

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

# Numpy. - lucru cu matrici

In [90]:
array2.reshape(2, 3)

array([[100., 120., 140.],
       [160., 180., 200.]])

In [91]:
array2.reshape(2, 3).T

array([[100., 160.],
       [120., 180.],
       [140., 200.]])

In [93]:
np.zeros(4)

array([0., 0., 0., 0.])

In [95]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [96]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [98]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [99]:
np.identity(6) * 3

array([[3., 0., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0.],
       [0., 0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 0., 3.]])

In [100]:
np.ones(4) * 3.3

array([3.3, 3.3, 3.3, 3.3])

# 2. Filter

In [103]:
array = np.random.randint(1, 100, 10)
array

array([23, 60, 95, 69, 54, 76, 97, 64,  1, 14])

In [105]:
array > 50

array([False,  True,  True,  True,  True,  True,  True,  True, False,
       False])

In [106]:
array [array > 50]

array([60, 95, 69, 54, 76, 97, 64])

In [107]:
array % 2 == 0

array([False,  True, False, False,  True,  True, False,  True, False,
        True])

In [112]:
print("initial:", array)
conditia1 = array % 2 == 0
conditia2 = array < 77

array [conditia1 & conditia2] 


initial: [23 60 95 69 54 76 97 64  1 14]


array([60, 54, 76, 64, 14])

In [109]:
True and False

False

In [116]:
True && False # nu functioneaza in Python

SyntaxError: invalid syntax (2297396071.py, line 1)

In [113]:
print("initial:", array)

conditia1 = array % 2 != 0
conditia2 = array > 77

array [conditia1 | conditia2] 

initial: [23 60 95 69 54 76 97 64  1 14]


array([23, 95, 69, 97,  1])

In [115]:
array [ (array % 2 != 0) | (array > 77) ] 

array([23, 95, 69, 97,  1])

# 3. Reduce

In [117]:
array = np.random.randint(1, 100, 10)
array

array([65, 97, 65, 38, 30, 99,  2, 88, 46, 76])

In [118]:
array.min()

np.int64(2)

In [123]:
min(array)

np.int64(2)

In [119]:
array.argmin()

np.int64(6)

In [120]:
array.sum()

np.int64(606)

In [124]:
sum(array)

np.int64(606)

In [122]:
array.mean()

np.float64(60.6)

In [125]:
len(array)

10

In [126]:
array.size

10

In [127]:
array.shape

(10,)

In [133]:
array = np.random.randint(1, 100, (4, 2))
array

array([[ 5, 60],
       [17, 85],
       [51, 61],
       [63, 66]])

In [134]:
array.shape

(4, 2)

In [135]:
array.shape[0]

4

In [130]:
array.size

8

In [137]:
array = np.random.randint(1, 100, (5, 6))
array

array([[47, 86, 32, 70, 71, 16],
       [71, 60, 88, 66, 66, 90],
       [25, 49, 26, 36, 15, 38],
       [74, 90, 81, 82, 73, 94],
       [66, 78, 20, 10, 30, 15]])

In [138]:
array.shape

(5, 6)

In [139]:
type(array.shape)

tuple

In [140]:
len(array.shape)

2

In [141]:
array = np.random.randint(1, 100, 10)
array

array([62, 33, 31, 74, 15,  8, 53,  9,  8, 22])

In [142]:
array.shape

(10,)

# Tuple

In [143]:
t = ()
print(t, type(t))

() <class 'tuple'>


In [144]:
t = (2, 3, 4)
print(t, type(t))

(2, 3, 4) <class 'tuple'>


In [145]:
t = (2)
print(t, type(t))

2 <class 'int'>


In [146]:
t = ((((2))))
print(t, type(t))

2 <class 'int'>


In [147]:
t = ((((2,))))
print(t, type(t))

(2,) <class 'tuple'>


In [148]:
t = 2,
print(t, type(t))

(2,) <class 'tuple'>


In [149]:
t = 2, 3
print(t, type(t))

(2, 3) <class 'tuple'>


In [ ]:
# unpacking
x, y = t
print("x=", x)
print("y=", y)

x= 2
y= 3


In [ ]:
x, y, z, *a = 2, 3, 4
print("x=", x)
print("y=", y)
print("z=", z)
print("a=", a)

x= 2
y= 3
z= 4
a= []


In [156]:
x, y, z, *a = 2, 3, 4, 7, 8, 8
print("x=", x)
print("y=", y)
print("z=", z)
print("a=", a)

x= 2
y= 3
z= 4
a= [7, 8, 8]


In [157]:
x = 20
y = "helllo"

x, y = y, x
print("x=", x)
print("y=", y)


x= helllo
y= 20


# Numpy indexare

In [159]:
array = np.random.randint(1, 100, (4, 3))
array

array([[87, 30, 20],
       [99, 35, 45],
       [22, 50, 93],
       [18, 27, 10]])

In [160]:
array[1]

array([99, 35, 45])

In [161]:
array[1][2]

np.int64(45)

In [162]:
array[1, 2]

np.int64(45)

In [163]:
array[ : , 1]

array([30, 35, 50, 27])

In [164]:
array[ : , 2]

array([20, 45, 93, 10])

In [166]:
array = np.random.randint(1, 100, (4, 3, 2))
array

array([[[16, 18],
        [34, 20],
        [11, 18]],

       [[54, 47],
        [81, 24],
        [77, 81]],

       [[17, 58],
        [92, 12],
        [91, 26]],

       [[59, 22],
        [22, 70],
        [38, 20]]])

In [167]:
array = np.random.randint(1, 100, (4, 3, 2, 1))
array

array([[[[91],
         [14]],

        [[44],
         [31]],

        [[99],
         [64]]],


       [[[72],
         [20]],

        [[63],
         [85]],

        [[66],
         [15]]],


       [[[19],
         [ 2]],

        [[18],
         [ 3]],

        [[ 7],
         [48]]],


       [[[ 4],
         [28]],

        [[90],
         [65]],

        [[86],
         [73]]]])